handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 1
    max-connections: 1
    threads:
      min-spare: 2
      max: 2
  compression:
    enabled: true
    min-response-size: 128

spring:
  resources:
    cache:
      cache-control:
        max-age: 365d
        public: true
    chain:
      strategy:
        content:
          enabled: true
          paths: /js/*
